### PR TITLE
fixes #12

### LINKED ISSUE #12: Illegal character ((CTRL-CHAR, code 27))
Getting following error on generated file. Looks like some characters needs to be encoded:

```sh
15:48:56.168 ERROR: Error during SonarQube Scanner execution
Error during parsing of generic test execution report '/home/runner/work/engine/engine/reports/jest-reporter.xml'. Look at the SonarQube documentation to know the expected XML format.
Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Illegal character ((CTRL-CHAR, code 27))
 at [row,col {unknown-source}]: [4,57]
	at com.ctc.wstx.sr.StreamScanner.throwInvalidSpace(StreamScanner.java:674)
	at com.ctc.wstx.sr.StreamScanner.throwInvalidSpace(StreamScanner.java:659)
	at com.ctc.wstx.sr.BasicStreamReader.parseAttrValue(BasicStreamReader.java:1918)
	at com.ctc.wstx.sr.BasicStreamReader.handleNonNsAttrs(BasicStreamReader.java:3139)
	at com.ctc.wstx.sr.BasicStreamReader.handleStartElem(BasicStreamReader.java:2968)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2839)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1073)
	at org.codehaus.staxmate.in.SMHierarchicCursor.getNext(SMHierarchicCursor.java:79)
```

Not related to #7, as testing with the fork version results in the same error.

### PR DESCRIPTION
**Pull request by tinovyatkin**
Fixes #12 and also potential problem with emoji in test title (both, ANSI color sequences and emoji are completely OK in Jest, but are problematic for XML). 
It introduces two small, but very well tested and maintained dependencies, so, I think it's future proof solution instead of maintaining proprietary code for escaping.

### CODE REVIEW

**Comment by sh33dafi** [comment]
Hi, thanks for the PR,  can you just change your commit message to follow the following format. https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary

If that's done I am happy to merge and publish a new version.

**Comment by tinovyatkin** [comment]
hmm. I see a lot of commits not following this convention: https://github.com/sh33dafi/jest-sonar/commits/master
Did you just decided to enforce starting this PR? 🤔

**Comment by tinovyatkin** [comment]
CI is failing now due to `yarn adudit`, all tests are passing well

**Comment by sh33dafi** [comment]
> hmm. I see a lot of commits not following this convention: https://github.com/sh33dafi/jest-sonar/commits/master
> Did you just decide to enforce starting this PR? 🤔

No but in the past I did not always follow it myself. :(
Still need to add commit lint for this and update the document.

I've just updated the master to fix the audit issue. If you can just merge in master everything should be ok!

**Pull request merged**
